import type { NextPage } from 'next'
import { useState, useEffect } from 'react'

// local utils
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

// local components
import { DenseTable } from "../src"

// external package
const axios = require('axios').default;


const Home: NextPage = () => {

  const [transactionsData, setTransactionsData] = useState<any[]>([])

  useEffect(() => {
    axios.get('/api/transaction-history')
    .then(function (response: any) {
      // handle success
      setTransactionsData(response.data)
      console.log(response.data);
    })
    .catch(function (error: any) {
      // handle error
      console.log(error);
    })
    .then(function () {
      // always executed
    });
  }, [])


  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://github.com/pranotoism/blockchain">Blockchain!</a>
        </h1>

        <p className={styles.description}>
          Transaction History
        </p>

        <DenseTable rows={transactionsData}></DenseTable>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://github.com/pranotoism/blockchain"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <code className={styles.code}>pranotoism</code>
        </a>
      </footer>
    </div>
  )
}

export default Home
